name: health_companion
description: "A comprehensive health tracking application with enhanced accessibility features for elderly users."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core Dependencies
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  provider: ^6.1.1
  get_it: ^7.6.7
  
  # UI Components
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  badges: ^3.1.2
  lottie: ^3.1.0
  fl_chart: ^0.69.0
  table_calendar: ^3.1.2
  intl: ^0.19.0
  
  # Accessibility & UI Enhancement
  flutter_tts: ^3.2.2
  speech_to_text: ^6.6.0
  vibration: ^1.8.4
  flutter_screenutil: ^5.9.0
  easy_localization: ^3.0.5
  flutter_displaymode: ^0.6.0
  
  # Health & Activity Tracking
  pedometer: ^4.0.2
  sensors_plus: ^4.0.2
  health: ^9.0.1
  
  # Notifications & Reminders
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2
  rxdart: ^0.27.7
  
  # Permissions & Device Features
  permission_handler: ^11.3.0
  device_info_plus: ^9.1.2
  package_info_plus: ^4.2.0
  
  # Network & API
  http: ^1.2.0
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1
  
  # Data Formatting & Parsing
  json_annotation: ^4.8.1
  
  # Audio & Media
  audioplayers: ^5.2.1
  camera: ^0.10.5+9
  image_picker: ^1.0.7
  
  # Database & Storage
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # URL Handling & External Links
  url_launcher: ^6.2.5
  share_plus: ^7.2.2
  
  # Security & Authentication
  local_auth: ^2.2.0
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  
  # UI Frameworks & Widgets
  flutter_markdown: ^0.6.20
  photo_view: ^0.14.0
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  # Development Tools
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  hive_generator: ^2.0.1
  
  # Testing
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

# Flutter Configuration
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/sounds/
    - assets/translations/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-regular.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  branding: assets/images/branding.png
  color_dark: "#000000"
  image_dark: assets/images/splash_dark.png
  branding_dark: assets/images/branding_dark.png

  android_12:
    image: assets/images/splash_android12.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/images/splash_android12_dark.png
    icon_background_color_dark: "#000000"
